/* Portfolio content — trilingual (EN / ES / EU), lifted from the real site's
   i18n strings so the language toggle behaves like jonramos.dev. */
window.DATA = {
  nav: {
    en: ['Home', 'Experience', 'Projects', 'Open Source', 'Contact'],
    es: ['Inicio', 'Experiencia', 'Proyectos', 'Open Source', 'Contacto'],
    eu: ['Hasiera', 'Esperientzia', 'Proiektuak', 'Kode Irekia', 'Kontaktua'],
  },
  hero: {
    en: {
      title: 'Software Engineer · Web Developer',
      desc: 'I build websites and web applications focused on high performance, data-driven solutions, and design. Astro for static sites, Clojure & ClojureScript for the complex ones. Based in Urnieta, Basque Country — currently building at ',
      view: 'View work', contact: 'Contact me',
    },
    es: {
      title: 'Ingeniero de Software · Desarrollador Web',
      desc: 'Construyo sitios y aplicaciones web centrados en alto rendimiento, soluciones orientadas a datos y diseño. Astro para sitios estáticos, Clojure y ClojureScript para los complejos. En Urnieta, País Vasco — actualmente en ',
      view: 'Ver trabajos', contact: 'Contáctame',
    },
    eu: {
      title: 'Software Ingeniaria · Web Garatzailea',
      desc: 'Errendimendu handiko web guneak eta aplikazioak eraikitzen ditut, datuetan eta diseinuan oinarrituta. Astro gune estatikoetarako, Clojure eta ClojureScript konplexuetarako. Urnietan, Euskal Herrian — gaur egun hemen: ',
      view: 'Lanak ikusi', contact: 'Kontaktatu',
    },
  },
  sections: {
    en: { exp: 'Experience', proj: 'Selected Projects', projSub: "A selection of things I've built and contributed to", os: 'Open Source', contact: 'Get in touch' },
    es: { exp: 'Experiencia', proj: 'Proyectos Seleccionados', projSub: 'Una selección de lo que he construido', os: 'Open Source', contact: 'Hablemos' },
    eu: { exp: 'Esperientzia', proj: 'Proiektu Hautatuak', projSub: 'Eraiki dudanaren hautaketa bat', os: 'Kode Irekia', contact: 'Jarri harremanetan' },
  },
  experience: {
    en: { since: 'since', present: 'Present', role: 'Software Engineer', desc: 'Building Naiha, a healthcare platform built with Clojure, ClojureScript and Datomic — robust, data-driven applications for the healthcare sector.' },
    es: { since: 'desde', present: 'Presente', role: 'Ingeniero de Software', desc: 'Desarrollando Naiha, una plataforma de salud con Clojure, ClojureScript y Datomic — aplicaciones robustas y orientadas a datos para el sector salud.' },
    eu: { since: 'noiztik', present: 'Orain', role: 'Software Ingeniaria', desc: 'Naiha garatzen, Clojure, ClojureScript eta Datomic erabiliz osasun plataforma bat — datuetan oinarritutako aplikazio sendoak osasun sektorerako.' },
  },
  projects: [
    { title: 'Naiha', type: 'WebApplication', tags: ['Clojure', 'ClojureScript', 'Datomic'], featured: true,
      desc: { en: 'A healthcare platform developed at Ubikare. Built with Clojure, ClojureScript and Datomic for robust data management.',
              es: 'Plataforma de salud desarrollada en Ubikare. Construida con Clojure, ClojureScript y Datomic para una gestión de datos robusta.',
              eu: 'Ubikaren garatutako osasun plataforma. Clojure, ClojureScript eta Datomic erabiliz datuen kudeaketa sendorako.' } },
    { title: 'Laguntza Fisioterapia', type: 'WebSite', tags: ['Astro', 'GSAP', 'TypeScript'],
      desc: { en: 'A multilingual physiotherapy clinic site with interactive Leaflet maps, GSAP animations and accessibility-first design.',
              es: 'Sitio multilingüe de clínica de fisioterapia con mapas Leaflet, animaciones GSAP y diseño accesible.',
              eu: 'Fisioterapia klinika eleaniztuna, Leaflet mapekin, GSAP animazioekin eta irisgarritasun diseinuarekin.' } },
    { title: 'Norwegian Singles', type: 'WebApp', tags: ['Astro', 'React', 'TypeScript'],
      desc: { en: 'A high-performance training-plan generator based on the Norwegian Singles methodology.',
              es: 'Generador de planes de entrenamiento basado en la metodología Norwegian Singles.',
              eu: 'Entrenamendu planak sortzeko tresna, Norwegian Singles metodologian oinarritua.' } },
    { title: 'Besaide M.E.', type: 'WebSite', tags: ['Astro', 'Keystatic', 'i18n'],
      desc: { en: 'A multilingual site for a Basque mountaineering association — i18n routing, accessible components, zero-JS navigation.',
              es: 'Sitio multilingüe para una asociación de montañismo vasca — enrutado i18n, componentes accesibles, navegación sin JS.',
              eu: 'Mendizale elkarte baten gune eleaniztuna — i18n bideratzea, osagai irisgarriak, JavaScript gabeko nabigazioa.' } },
    { title: 'color-tools', type: 'Library', tags: ['Clojure', 'Open Source'],
      desc: { en: 'A Clojure(Script) library for colour manipulation and conversion. Open-source.',
              es: 'Librería Clojure(Script) para manipulación y conversión de colores. Open source.',
              eu: 'Koloreak manipulatu eta bihurtzeko Clojure(Script) liburutegia. Kode irekia.' } },
    { title: 'jon-nested-menu', type: 'Library', tags: ['ClojureScript', 'React', 'MUI'],
      desc: { en: 'A nested MUI menu library for Reagent/ClojureScript & React. Published to Clojars and npm.',
              es: 'Librería de menús MUI anidados para Reagent/ClojureScript y React. En Clojars y npm.',
              eu: 'MUI menu habiaratuen liburutegia Reagent/ClojureScript eta React-erako. Clojars eta npm-en.' } },
  ],
  contributions: {
    en: { merged: 'Merged PRs', projects: 'Projects', techs: 'Technologies', sub: 'Contributions to Clojure tooling & developer experience' },
    es: { merged: 'PRs fusionados', projects: 'Proyectos', techs: 'Tecnologías', sub: 'Contribuciones a herramientas Clojure y experiencia de desarrollador' },
    eu: { merged: 'Bateratutako PRak', projects: 'Proiektuak', techs: 'Teknologiak', sub: 'Clojure tresnetarako eta garatzaile esperientziarako ekarpenak' },
    repos: ['clj-kondo', 'cljfmt', 'Logseq', 'Calva', 'medley'],
  },
  contact: {
    en: { text: 'Software developer in Urnieta, Basque Country. Available for professional connections and technical discussions.',
          formTitle: 'Send a message', formDesc: "Got a question or a proposal? I'll get back to you shortly.",
          name: 'Name', email: 'Email', message: 'Message', send: 'Send message', sent: 'Message sent — talk soon.' },
    es: { text: 'Desarrollador de software en Urnieta, País Vasco. Disponible para conexiones profesionales y discusiones técnicas.',
          formTitle: 'Envía un mensaje', formDesc: '¿Una pregunta o propuesta? Te responderé pronto.',
          name: 'Nombre', email: 'Correo', message: 'Mensaje', send: 'Enviar mensaje', sent: 'Mensaje enviado — hablamos pronto.' },
    eu: { text: 'Software garatzailea Urnietan, Euskal Herrian. Konexio profesionaletarako eta eztabaida teknikoetarako prest.',
          formTitle: 'Bidali mezua', formDesc: 'Galdera edo proposamenik? Laster erantzungo dizut.',
          name: 'Izena', email: 'Emaila', message: 'Mezua', send: 'Mezua bidali', sent: 'Mezua bidalita — laster arte.' },
  },
};
